apiVersion: v2
name: platform-services
description: Manages applications providing cluster-wide services.
type: application
version: 0.2.0
appVersion: 0.2.0
home: https://github.com/kbrockhoff/aws-black-belt-containers
