environment: dev
baseDomain: api.bbckb.k8sgreen.trng.aws.daughertylabs.io
platformApps:
  - name: argo-rollouts
    cascadeDelete: false
    project: platform
    namespace: argo-rollouts
    repo:
      path: workloads/argo-rollouts
      revision: main
    helm: {}
    syncPolicy:
      prune: true
      selfHeal: true
      wave: 1
  - name: cost-analyzer
    cascadeDelete: false
    project: platform
    namespace: kubecost
    repo:
      path: workloads/opencost
      revision: main
    helm: {}
    syncPolicy:
      prune: true
      selfHeal: true
      wave: 1
  - name: argocd-monitoring
    cascadeDelete: false
    project: platform
    namespace: monitoring
    repo:
      path: workloads/argocd-monitoring
      revision: main
    helm: {}
    syncPolicy:
      prune: true
      selfHeal: true
      wave: 2
