controller:
  tolerations:
    - key: "daughertylabs.io/availability"
      operator: "Equal"
      value: "preemptable"
      effect: "NoSchedule"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

dashboard:
  enabled: true
  tolerations:
    - key: "daughertylabs.io/availability"
      operator: "Equal"
      value: "preemptable"
      effect: "NoSchedule"
