redis-ha:
  enabled: false

controller:
  enableStatefulSet: true
  metrics:
    enabled: true

server:
  autoscaling:
    enabled: true
    minReplicas: 1
  metrics:
    enabled: true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true
