global:
  ## Override the deployment namespace
  namespaceOverride: logging

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ${service_account_name}

cloudWatch:
  enabled: true
  match: "*"
  region: ${aws_region}
  logGroupName: ${log_group_name}
  logStreamName:
  logStreamPrefix: "fluentbit-"
  logKey:
  logFormat:
  roleArn:
  autoCreateGroup: true
  endpoint:
  credentialsEndpoint:  {}

firehose:
  enabled: false
  region: ${aws_region}

kinesis:
  enabled: false
  region: ${aws_region}

elasticsearch:
  enabled: false
  region: ${aws_region}

service:
  parsersFiles:
    - /fluent-bit/parsers/parsers.conf
  # extraParsers: |
  #   [PARSER]
  #       Name   logfmt
  #       Format logfmt

input:
  tag: "kube.*"
  path: "/var/log/containers/*.log"
  db: "/var/log/flb_kube.db"
  parser: docker
  dockerMode: "On"
  memBufLimit: 5MB
  skipLongLines: "On"
  refreshInterval: 10

 extraInputs: |
   [INPUT]
       Name         winlog
       Channels     Setup,Windows PowerShell
       Interval_Sec 1
       DB           winlog.sqlite


filter:
  match: "kube.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "On"
  mergeLogKey: "data"
  keepLog: "On"
  k8sLoggingParser: "On"
  k8sLoggingExclude: "On"

# extraFilters: |
#   [FILTER]
#       Name   grep
#       Match  *
#       Exclude log lvl=debug*

resources:
  limits:
    memory: 250Mi
  requests:
    cpu: 50m
    memory: 50Mi

## Assign a PriorityClassName to pods if set
# priorityClassName: system-node-critical

updateStrategy:
  type: RollingUpdate

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}

annotations: {}
# iam.amazonaws.com/role: arn:aws:iam::123456789012:role/role-for-fluent-bit

env: []

volumes:
  - name: varlog
    hostPath:
      path: /var/log

volumeMounts:
  - name: varlog
    mountPath: /var/log
