${yamlencode({
  alertManager = {
    ingress = {
      enabled = true
      ingressClassName = "nginx"
      annotations = {
        "cert-manager.io/cluster-issuer" = "cert-manager-ca"
      }
      hosts = alertmanager_hosts
      path = "/"
      tls = [{
        secretName = "alertmanager-general-tls"
        hosts = alertmanager_hosts
      }]
    }
  }
  grafana = {
    tolerations = [
      {
         key = "daughertylabs.io/availability"
         operator = "Equal"
         value = "preemptable"
         effect = "NoSchedule"
      }
    ]
    ingress = {
      enabled = true
      ingressClassName = "nginx"
      annotations = {
        "cert-manager.io/cluster-issuer" = "cert-manager-ca"
      }
      hosts = grafana_hosts
      path = "/"
      tls = [{
        secretName = "grafana-general-tls"
        hosts = grafana_hosts
      }]
    }
  }
})}
