configuration:
  provider: aws
  backupStorageLocation:
    bucket: ${backup_s3_bucket}

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.4.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

upgradeCRDs: false
