{{- $root := .Values }}
{{- $values := concat $root.platformApps ($root.workloadApps | default (list)) }}
{{ range $values }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $root.Namespace | default "argocd" }}
  {{- if .cascadeDelete }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{ end }}
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ .repo.url | default "https://github.com/kbrockhoff/aws-black-belt-containers" | squote }}
    {{- if .repo.revision}}
    targetRevision: {{ .repo.revision }}
    {{- else }}
    targetRevision: main
    {{- end }}
    {{- if .repo.path }}
    path: {{ .repo.path }}
    {{- end }}
    {{- if or .helm (not (kindIs "invalid" .helm)) }}
    helm:
      parameters:
        - name: environment
          value: {{ $root.environment }}
        - name: base_domain_name
          value: {{ $root.base_domain_name }}
      {{- if .helm.parameters }}
      {{- toYaml .helm.parameters | nindent 8 }}
      {{- end }}
      {{- if .helm.valueFiles }}
      valueFiles:
      {{- toYaml .helm.valueFiles | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if or .directory (not (kindIs "invalid" .directory)) }}
    directory:
      recurse: {{ .directory.recurse }}
    {{- end }}
  destionation:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .namespace }}
  {{- if .syncPolicy }}
  syncPolicy:
    retry:
      limit: 4
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 30m
      automated:
        prune: {{ .syncPolicy.prune | default "false" }}
        selfHeal: {{ .syncPolicy.selfHeal | default "false" }}
  {{- end }}
  {{- if .ignoreDifferences }}
  ignoreDifferences:
  {{- toYaml .ignoreDifferences | nindent 4 }}
  {{- end }}
{{ end }}
