name: AWS Cleanup

on:
  workflow_dispatch:
    inputs:
      cmd:
        description: 'CLI Command'
        required: true

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: /home/runner

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::838520979566:role/dl-aws-k8strng-sbox-kbgithub
          aws-region: us-west-2

      - name: Execute command
        run: ${{ github.event.inputs.cmd }}
